import { createHash } from 'crypto'
import { existsSync, readFileSync, writeFileSync } from 'fs'
import { session } from 'electron'
import { getCookiesPath } from './paths'

export const YTM_LOGIN_PARTITION = 'persist:ytm-login'

export interface ParsedNetscapeCookie {
  domain: string
  path: string
  secure: boolean
  name: string
  value: string
}

export function parseNetscapeCookies(content: string): ParsedNetscapeCookie[] {
  const cookies: ParsedNetscapeCookie[] = []

  for (const line of content.split('\n')) {
    if (!line || line.startsWith('#')) continue
    const parts = line.split('\t')
    if (parts.length < 7) continue
    cookies.push({
      domain: parts[0],
      path: parts[2] || '/',
      secure: parts[3] === 'TRUE',
      name: parts[5],
      value: parts.slice(6).join('\t')
    })
  }

  return cookies
}

function isYtDlpExportableDomain(domain: string): boolean {
  const normalized = domain.toLowerCase()
  return normalized.includes('youtube.com') && !normalized.includes('accounts.google.com')
}

export function isYtDlpExportableCookie(cookie: {
  domain?: string
  name: string
  value: string
}): boolean {
  const domain = cookie.domain || ''
  if (!isYtDlpExportableDomain(domain)) return false
  if (cookie.name.startsWith('__Host-')) return false
  if (cookie.value.includes('\t') || cookie.value.includes('\n') || cookie.value.includes('\r')) {
    return false
  }
  return true
}

function electronCookieToNetscapeLine(cookie: Electron.Cookie): string | null {
  if (!isYtDlpExportableCookie(cookie)) return null

  const domain = '.youtube.com'
  const path = cookie.path || '/'
  const secure = cookie.secure ? 'TRUE' : 'FALSE'
  const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0
  return `${domain}\tTRUE\t${path}\t${secure}\t${expires}\t${cookie.name}\t${cookie.value}`
}

function parsedCookieToNetscapeLine(cookie: ParsedNetscapeCookie): string | null {
  if (!isYtDlpExportableCookie(cookie)) return null

  const domain = '.youtube.com'
  const path = cookie.path || '/'
  const secure = cookie.secure ? 'TRUE' : 'FALSE'
  return `${domain}\tTRUE\t${path}\t${secure}\t0\t${cookie.name}\t${cookie.value}`
}

export function writeYtDlpCookiesFile(
  cookies: Electron.Cookie[],
  filePath = getCookiesPath()
): void {
  const lines = ['# Netscape HTTP Cookie File', '# This file was generated by ytm-synk']
  const seen = new Set<string>()

  for (const cookie of cookies) {
    const line = electronCookieToNetscapeLine(cookie)
    if (!line) continue
    const key = line.split('\t')[5]
    if (seen.has(key)) continue
    seen.add(key)
    lines.push(line)
  }

  writeFileSync(filePath, `${lines.join('\n')}\n`, 'utf-8')
}

export function writeYtDlpCookiesFromParsed(
  cookies: ParsedNetscapeCookie[],
  filePath = getCookiesPath()
): void {
  const lines = ['# Netscape HTTP Cookie File', '# This file was generated by ytm-synk']
  const seen = new Set<string>()

  for (const cookie of cookies) {
    const line = parsedCookieToNetscapeLine(cookie)
    if (!line) continue
    const key = line.split('\t')[5]
    if (seen.has(key)) continue
    seen.add(key)
    lines.push(line)
  }

  writeFileSync(filePath, `${lines.join('\n')}\n`, 'utf-8')
}

export async function refreshYtDlpCookiesFile(filePath = getCookiesPath()): Promise<void> {
  const loginSession = session.fromPartition(YTM_LOGIN_PARTITION)
  const partitionCookies = await loginSession.cookies.get({})
  const youtubeCookies = partitionCookies.filter((cookie) =>
    (cookie.domain || '').includes('youtube.com')
  )

  if (youtubeCookies.length > 0) {
    const header = youtubeCookies.map((cookie) => `${cookie.name}=${cookie.value}`).join('; ')
    if (hasAuthCookies(header)) {
      writeYtDlpCookiesFile(youtubeCookies, filePath)
      return
    }
  }

  if (!existsSync(filePath)) return
  const parsed = parseNetscapeCookies(readFileSync(filePath, 'utf-8'))
  writeYtDlpCookiesFromParsed(parsed, filePath)
}

export function cookiesToHeader(cookies: ParsedNetscapeCookie[]): string {
  return cookies.map((c) => `${c.name}=${c.value}`).join('; ')
}

export function readCookieHeader(filePath = getCookiesPath()): string | null {
  if (!existsSync(filePath)) return null
  const cookies = parseNetscapeCookies(readFileSync(filePath, 'utf-8'))
  if (cookies.length === 0) return null
  return cookiesToHeader(cookies)
}

export function readYoutubeCookieHeader(filePath = getCookiesPath()): string | null {
  if (!existsSync(filePath)) return null
  const cookies = parseNetscapeCookies(readFileSync(filePath, 'utf-8')).filter((cookie) =>
    cookie.domain.includes('youtube.com')
  )
  if (cookies.length === 0) return null
  return cookiesToHeader(cookies)
}

export function hasAuthCookiesInFile(filePath = getCookiesPath()): boolean {
  const header = readYoutubeCookieHeader(filePath) ?? readCookieHeader(filePath)
  if (!header) return false
  return hasAuthCookies(header)
}

export function hasAuthCookies(cookieHeader: string): boolean {
  const hasSession =
    cookieHeader.includes('__Secure-3PSID=') ||
    cookieHeader.includes('__Secure-1PSID=') ||
    cookieHeader.includes('SID=')
  const hasSapisid =
    cookieHeader.includes('SAPISID=') || cookieHeader.includes('__Secure-3PAPISID=')
  return hasSession && hasSapisid
}

function extractCookieValue(cookieHeader: string, name: string): string | null {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = cookieHeader.match(new RegExp(`(?:^|; )${escaped}=([^;]*)`))
  return match?.[1] ?? null
}

function getSidSecrets(cookieHeader: string): {
  sapisid: string | null
  papisid1: string | null
  papisid3: string | null
} {
  return {
    sapisid:
      extractCookieValue(cookieHeader, 'SAPISID') ??
      extractCookieValue(cookieHeader, '__Secure-3PAPISID'),
    papisid1: extractCookieValue(cookieHeader, '__Secure-1PAPISID'),
    papisid3: extractCookieValue(cookieHeader, '__Secure-3PAPISID')
  }
}

function makeSidAuthorization(scheme: string, secret: string, origin: string): string {
  const timestamp = Math.floor(Date.now() / 1000)
  const hash = createHash('sha1').update(`${timestamp} ${secret} ${origin}`).digest('hex')
  return `${scheme} ${timestamp}_${hash}`
}

export function buildAuthorizationHeader(
  cookieHeader: string,
  origin = 'https://music.youtube.com'
): string | null {
  const { sapisid, papisid1, papisid3 } = getSidSecrets(cookieHeader)
  const parts = [
    sapisid ? makeSidAuthorization('SAPISIDHASH', sapisid, origin) : null,
    papisid1 ? makeSidAuthorization('SAPISID1PHASH', papisid1, origin) : null,
    papisid3 ? makeSidAuthorization('SAPISID3PHASH', papisid3, origin) : null
  ].filter((part): part is string => Boolean(part))

  return parts.length > 0 ? parts.join(' ') : null
}

export function electronCookiesToApiHeader(cookies: Electron.Cookie[]): string {
  const youtubeCookies = cookies.filter((cookie) => (cookie.domain || '').includes('youtube.com'))
  const source = youtubeCookies.length > 0 ? youtubeCookies : cookies
  return source.map((cookie) => `${cookie.name}=${cookie.value}`).join('; ')
}

export function writeNetscapeCookiesFromElectron(
  cookies: Electron.Cookie[],
  filePath = getCookiesPath()
): void {
  writeYtDlpCookiesFile(
    cookies.filter((cookie) => (cookie.domain || '').includes('youtube.com')),
    filePath
  )
}

function cookieDomainToUrl(domain: string, path: string): string {
  const host = domain.replace(/^\./, '')
  const protocol = host.includes('google') || host.includes('youtube') ? 'https' : 'https'
  return `${protocol}://${host}${path || '/'}`
}

export async function syncNetscapeCookiesToSession(filePath = getCookiesPath()): Promise<void> {
  if (!existsSync(filePath)) return

  const loginSession = session.fromPartition(YTM_LOGIN_PARTITION)
  const cookies = parseNetscapeCookies(readFileSync(filePath, 'utf-8')).filter((cookie) =>
    isYtDlpExportableDomain(cookie.domain)
  )

  for (const cookie of cookies) {
    try {
      await loginSession.cookies.set({
        url: cookieDomainToUrl(cookie.domain, cookie.path),
        name: cookie.name,
        value: cookie.value,
        domain: cookie.domain.startsWith('.') ? cookie.domain : `.${cookie.domain}`,
        path: cookie.path || '/',
        secure: cookie.secure,
        httpOnly: false
      })
    } catch {
      // Some exported cookies cannot be re-imported into Chromium.
    }
  }
}

type AxiosLikeConfig = {
  url?: string
  baseURL?: string
  method?: string
  headers: Record<string, string>
  data?: unknown
  params?: Record<string, string>
  responseType?: string
}

type AxiosLikeResponse = {
  data: unknown
  status: number
  statusText: string
  headers: Record<string, string>
  config: AxiosLikeConfig
}

function buildRequestUrl(config: AxiosLikeConfig): string {
  const base = config.baseURL ?? ''
  const path = config.url ?? ''
  const url = new URL(path, base.endsWith('/') ? base : `${base}/`)
  if (config.params) {
    for (const [key, value] of Object.entries(config.params)) {
      url.searchParams.set(key, value)
    }
  }
  return url.toString()
}

function createElectronSessionAdapter(loginSession: Electron.Session) {
  return async (config: AxiosLikeConfig): Promise<AxiosLikeResponse> => {
    const url = buildRequestUrl(config)
    const headers = new Headers()
    for (const [key, value] of Object.entries(config.headers)) {
      if (value !== undefined && value !== null) {
        headers.set(key, String(value))
      }
    }

    const method = (config.method ?? 'get').toUpperCase()
    const body =
      config.data === undefined || config.data === null
        ? undefined
        : typeof config.data === 'string'
          ? config.data
          : JSON.stringify(config.data)

    const response = await loginSession.fetch(url, { method, headers, body })
    const text = await response.text()
    const data =
      config.responseType === 'json'
        ? (() => {
            try {
              return JSON.parse(text)
            } catch {
              return text
            }
          })()
        : text

    const responseHeaders: Record<string, string> = {}
    response.headers.forEach((value, key) => {
      responseHeaders[key] = value
    })

    return {
      data,
      status: response.status,
      statusText: response.statusText,
      headers: responseHeaders,
      config
    }
  }
}

type YtmAxiosClient = {
  defaults: { headers: Record<string, unknown> }
  interceptors: {
    request: { use: (fn: (config: { headers: Record<string, string> }) => unknown) => number }
  }
}

export type YtmCookieClient = {
  cookiejar: {
    getCookieStringSync: (url?: string) => string
    setCookieSync: (...args: unknown[]) => unknown
  }
  client: YtmAxiosClient
  initialize: (options?: { cookies?: string }) => Promise<unknown>
  constructRequest: (
    endpoint: string,
    body?: Record<string, unknown>,
    query?: Record<string, string>
  ) => Promise<unknown>
}

export function configureYtmusicClient(client: YtmCookieClient, cookieHeader: string): void {
  const loginSession = session.fromPartition(YTM_LOGIN_PARTITION)

  client.cookiejar = {
    getCookieStringSync: () => cookieHeader,
    setCookieSync: () => undefined
  }

  ;(client.client.defaults as { adapter?: unknown }).adapter =
    createElectronSessionAdapter(loginSession)

  client.client.interceptors.request.use((config) => {
    const origin = 'https://music.youtube.com'
    const authorization = buildAuthorizationHeader(cookieHeader, origin)
    if (authorization) config.headers.Authorization = authorization
    config.headers.Origin = origin
    config.headers['X-Origin'] = origin
    // Keep Cookie in sync with the SAPISIDHASH secret (do not rely only on partition cookies).
    config.headers.Cookie = cookieHeader
    config.headers.cookie = cookieHeader
    return config
  })
}

function isGuestPayload(payload: string): boolean {
  return (
    payload.includes('Looking for what you') ||
    payload.includes('SIGN_IN') ||
    payload.includes('"logged_in",0') ||
    payload.includes('"key":"logged_in","value":"0"') ||
    payload.includes('"value":"0","key":"logged_in"')
  )
}

function isAuthenticatedPayload(payload: string): boolean {
  if (isGuestPayload(payload)) return false
  return (
    payload.includes('"logged_in","value":"1"') ||
    payload.includes('"key":"logged_in","value":"1"') ||
    payload.includes('accountName') ||
    payload.includes('channelHandle') ||
    payload.includes('musicResponsiveListItemRenderer') ||
    payload.includes('musicTwoRowItemRenderer') ||
    payload.includes('gridRenderer') ||
    payload.includes('playlistVideoRenderer') ||
    payload.includes('musicPlaylistShelfRenderer') ||
    payload.includes('musicEditablePlaylistDetailHeaderRenderer')
  )
}

async function canBrowsePlaylist(client: YtmCookieClient, playlistId: string): Promise<boolean> {
  try {
    const browseId = playlistId.startsWith('VL') ? playlistId : `VL${playlistId}`
    const response = await client.constructRequest('browse', { browseId })
    return isAuthenticatedPayload(JSON.stringify(response))
  } catch {
    return false
  }
}

export async function verifyYtmusicSession(client: YtmCookieClient): Promise<boolean> {
  try {
    const account = await client.constructRequest('account/account_menu', {})
    if (isAuthenticatedPayload(JSON.stringify(account))) return true

    if (await canBrowsePlaylist(client, 'LM')) return true

    const library = await client.constructRequest('browse', { browseId: 'FEmusic_liked_playlists' })
    return isAuthenticatedPayload(JSON.stringify(library))
  } catch {
    return false
  }
}

export function parsePlaylistId(input: string): string | null {
  const trimmed = input.trim()
  if (!trimmed) return null
  if (/^(PL|LM|OLAK|VL)/.test(trimmed)) {
    return trimmed.startsWith('VL') ? trimmed.slice(2) : trimmed
  }
  const listMatch = trimmed.match(/[?&]list=([^&]+)/)
  if (listMatch?.[1]) {
    const id = decodeURIComponent(listMatch[1])
    return id.startsWith('VL') ? id.slice(2) : id
  }
  return null
}
